### ISSUE TITLE
Upgrade roadmap to newest versions of nf-core template

### ISSUE THREAD

**Issue by luiskuhn** [qbic-pipelines/root-tissue-analysis#32]
**Feedback from peer-review:**

- [ ] Fix warning:  `WARN: Access to undefined parameter 'enable_conda' -- Initialise it to a default value eg. 'params.enable_conda = some_value'`
- [ ] Include input validation using the nf-validation plugin to replace `SAMPLESHEET_CHECK`:
https://github.com/qbic-pipelines/root-tissue-analysis/blob/b8c687630405bd9b86a32da60fcaf217aa5e4492/modules/local/samplesheet_check.nf#L6
- [ ] Update to the newest versions of the nf-core template (https://nf-co.re/docs/tutorials/nextflow_training/creating_with_nf-core)
